
export const words = [
    {id: 1, english: "mama", transcription: "mama", translate: "mama", example: "mama"},
    {id: 2, english: "to suffocate", transcription: "[ˈsʌf.ə.keɪt]", translate: "задихнутися", example: "He said he'd suffocate if he remained in this house for another hour."},
    {id: 3, english: "aftermath", transcription: "[ˈɑːf.tə.mæθ]", translate: "наслідок", example: "Food prices soared in the aftermath of the drought."},
    {id: 4, english: "is collected", transcription: "|kəˈlektɪd|", translate: "зібраний", example: "She seemed completely cool, calm, and collected during her speech."},
    {id: 5, english: "shade", transcription: "[ʃeɪd]", translate: "тінь", example: "Sitting in the shade."},
    {id: 6, english: "in time", transcription: "[taɪm]", translate: "вчасно", example: "Just-in-time production."},
    {id: 7, english: "to convince", transcription: "[kənˈvɪns]", translate: "переконати", example: "You couldn't convince him that a floppy disk was as good as a manuscript."},
    {id: 8, english: "to persuade", transcription: "[pərˈsweɪd]", translate: "вговорити", example: "To persuade to vote for the Democratic Party."},
    {id: 9, english: "to be used to", transcription: "[juːst]", translate: "звикнути", example: "To be used to the cold."},
    {id: 10, english: "habit", transcription: "[ˈhæbɪt]", translate: "звичка", example: "This can develop into a bad habit."},
    {id: 11, english: "jealous", transcription: "|ˈdʒeləs|", translate: "ревнивий", example: "Is Luke jealous of Jay?"},
    {id: 12, english: "envious", transcription: "|ˈenvɪəs|", translate: "заздрісний", example: "He is so envious of her success."},
    {id: 13, english: "ought to", transcription: "|ˈɔːt|", translate: "повинен", example: "A statement of what ought to be the case as contrasted to what is the case."},
    {id: 14, english: "liberty", transcription: "|ˈlɪbərtɪ|", translate: "свобода; воля", example: "They gave him the liberty to handle the problem himself."},
    {id: 15, english: "to split", transcription: "|splɪt|", translate: "розділити", example: "She split the muffin and gave me half."},
    {id: 16, english: "humiliating", transcription: "|hjuːˈmɪlɪeɪtɪŋ|", translate: "принизливий", example: "It is humiliating to take orders from him."},
    {id: 17, english: "to cure", transcription: "|kjʊr|", translate: "вилікувати", example: "The infection can be cured with antibiotics."},
    {id: 18, english: "to heals", transcription: "|ˈhiːlz|", translate: "лікувати", example: "Time heals."},
    {id: 19, english: "due to", transcription: "|duː|", translate: "через; завдяки", example: "Due to updates to your phone."},
    {id: 20, english: "to reward", transcription: "|rɪˈwɔːrd|", translate: "нагороджувати", example: "Hard work brings its own rewards."},
    {id: 21, english: "to award", transcription: "|əˈwɔːrd|", translate: "нагороджувати; присуджувати", example: "The winner was awarded a gold medal."},
    {id: 22, english: "to confer", transcription: "|kənˈfɜːr|", translate: "присвоювати", example: "The university conferred a degree on its most famous former student, who never graduated."},
    {id: 23, english: "diary", transcription: "|ˈdaɪərɪ|", translate: "щоденник", example: "Did you put the meeting date in your diary?"},
    {id: 24, english: "journey", transcription: "|ˈdʒɜːrnɪ|", translate: "подорож", example: "She was the first woman to journey into space."},
    {id: 25, english: "sane", transcription: "|seɪn|", translate: "здорового глузду", example: "No sane person could do something so horrible."},
    {id: 26, english: "among", transcription: "|əˈmʌŋ|", translate: "серед; поміж", example: "The house is nestled among the trees."},
    {id: 27, english: "anxious", transcription: "|ˈæŋkʃəs|", translate: "занепокоєний", example: "She feels anxious and depressed."},
    {id: 28, english: "eager", transcription: "|ˈiːɡər|", translate: "охоче; нетерплячий", example: "She was eager to get started."},
    {id: 29, english: "loose", transcription: "|luːs|", translate: "вільний; нетугий", example: "Some of the shingles had come loose."},
    {id: 30, english: "quite", transcription: "|kwaɪt|", translate: "цілком; дійсно", example: "I am quite capable of doing it myself, thank you."},
    {id: 31, english: "sensible", transcription: "|ˈsensəbl|", translate: "розумний", example: "My teacher gave me some sensible advice."},
    {id: 32, english: "headline", transcription: "|ˈhedlaɪn|", translate: "заголовок", example: "The story of his arrest appeared beneath the headline “Caught!”."},
    {id: 33, english: "priceless", transcription: "|ˈpraɪsləs|", translate: "безцінний", example: "The look on his face was priceless."},
    {id: 34, english: "I wish I were", transcription: "", translate: "Я б хотів бути", example: ""},
    {id: 35, english: "particular", transcription: "|pərˈtɪkjələr|", translate: "особливий", example: "Our teacher is very particular when it comes to punctuation."},
    {id: 36, english: "briefly", transcription: "|ˈbriːflɪ|", translate: "коротко", example: "Please briefly describe your experience."},
    {id: 37, english: "shortly", transcription: "|ˈʃɔːrtlɪ|", translate: "незабаром", example: "We arrived shortly after six o'clock."},
    {id: 38, english: "continuously", transcription: "|kənˈtɪnjʊəslɪ|", translate: "безперервно", example: "The function is continuously differentiable."},
    {id: 39, english: "worthless", transcription: "|ˈwɜːrθləs|", translate: "нікчемний", example: "The information was worthless to me."},
    {id: 40, english: "to remind", transcription: "|rɪˈmaɪnd|", translate: "нагадати", example: "Remind me to buy some groceries after work."},
    {id: 41, english: "to blame", transcription: "|bleɪm|", translate: "звинувачувати", example: "Don't blame me. You are responsible for your own problems."},
    {id: 42, english: "fault", transcription: "|fɔːlt|", translate: "провина", example: "Lack of courage is his worst fault."},
    {id: 43, english: "advertisement", transcription: "|ˌædvərˈtaɪzmənt|", translate: "реклама", example: "The advertisement will appear in three magazines."},
    {id: 44, english: "although", transcription: "|ɔːlˈðəʊ|", translate: "хоча", example: "No, this is my responsibility, although I appreciate your offer."},
    {id: 45, english: "responsibility", transcription: "|rɪˌspɑːnsəˈbɪlətɪ|", translate: "відповідальність", example: "Mowing the lawn is your responsibility."},
    {id: 46, english: "however", transcription: "|haʊˈevər|", translate: "однак; проте", example: "Do it however you like."},
    {id: 47, english: "to divert", transcription: "|daɪˈvɜːrt|", translate: "відвернути; відхиляти", example: "Police diverted traffic to a side street."},
    {id: 48, english: "to distract", transcription: "|dɪˈstrækt|", translate: "відволікати", example: "I was distracted by a loud noise."},
    {id: 49, english: "to put off", transcription: "", translate: "відкласти", example: ""},
    {id: 50, english: "to defend", transcription: "|dɪˈfend|", translate: "захищати", example: "The company must defend its own interests."},
    {id: 51, english: "to devote", transcription: "|dɪˈvəʊt|", translate: "присвятити", example: "We devote five full days a month to training."},
    {id: 52, english: "to beat", transcription: "|biːt|", translate: "бити", example: "She used a hammer to beat the metal into shape."},
    {id: 53, english: "common", transcription: "|ˈkɑːmən|", translate: "загальний", example: "The people on the island have a sense of common identity."},
    {id: 54, english: "to grumble", transcription: "|ˈɡrʌmbl|", translate: "бурчати; скаржитися", example: "Fans grumbled about the team's poor play."},
    {id: 55, english: "fee", transcription: "|fiː|", translate: "плата; гонорар", example: "They paid a fortune in legal fees."},
    {id: 56, english: "astonished", transcription: "|əˈstɑːnɪʃt|", translate: "здивований", example: "I was astonished by the result."},
    {id: 57, english: "to break out", transcription: "|ˈbreɪk ˈaʊt|", translate: "утекти; спалахнути", example: "1.Three men broke out of prison yesterday.\n 2.I break out in a rash if I eat shellfish.\n 3.To break out in laughter."},
    {id: 58, english: "offensive", transcription: "|əˈfensɪv|", translate: "образливий", example: "His actions were offensive to everyone."},
    {id: 58, english: "to pare", transcription: "|per|", translate: "підрізати; обрізати", example: "The company has to find a way to pare expenses."},
    {id: 58, english: "", transcription: "", translate: "", example: ""},
]