export const wordsGerman = 
[
    {id: 1, english: "", transcription: "", translate: "", example: ""},
    {id: 2, english: "morning", transcription: "[ˈmɔːnɪŋ]", translate: "Morgen; Vormittag", example: "I have breakfast in the kitchen every morning."},
    {id: 3, english: "stepmum", transcription: "[ˈstepˌmʌm]", translate: "Stiefmutter", example: ""},
    {id: 4, english: "if", transcription: "[ɪf]", translate: "wenn; falls; ob", example: "If it's a nice day, we can go to the park."},
    {id: 5, english: "till", transcription: "[tɪl]", translate: "bis", example: "My English lesson is from 8:30 till 9:15 today."},
    {id: 6, english: "after that", transcription: "[ˈæftər] [ðæt]", translate: "danach", example: ""},
    {id: 7, english: "on Mondays", transcription: "[ˈmʌndeɪ]", translate: "montags", example: ""},
    {id: 8, english: "netball", transcription: "", translate: "Korbball", example: "Netball is a popular girl's game at British schools."},
    {id: 9, english: "other", transcription: "[ˈʌðər]", translate: "anders; andere; weitere", example: "Is there only your family in your house, or are there other people too?"},
    {id: 11, english: "right away", transcription: "|ˈraɪt əˈweɪ|", translate: "sofort; gleich", example: "Can I watch TV now, Mum? -No, Dave. It's best to do your homework right away."},
    {id: 12, english: "often", transcription: "|ˈɔːfn|", translate: "oft; häufig", example: "At TTS there are often clubs after school."},
    {id: 13, english: "in the evenings", transcription: "|ˈiːvnɪŋz|", translate: "abends", example: "We often watch TV in the evenings. You too?"},
    {id: 14, english: "evening", transcription: "|ˈiːvnɪŋz|", translate: "Abend", example: ""},
    {id: 15, english: "sometimes", transcription: "|ˈsʌmtaɪmz|", translate: "manchmal", example: ""},
    {id: 16, english: "usually", transcription: "|ˈjuːʒʊəlɪ|", translate: "normalerweise; gewöhnlich; meistens", example: "always - usually - often - sometimes - never"},
    {id: 17, english: "long", transcription: "|lɔːŋ|", translate: "lang", example: "How long are lessons at TTS?"},
    {id: 18, english: "I'm dog-tired", transcription: "|dɒɡˈtaɪəd| ", translate: "Ich bin hundemüde", example: ""},
    {id: 19, english: "tired", transcription: "|taɪrd|", translate: "müde", example: "I don't want to watch TV. I'm tired."},
    {id: 20, english: "What about...?", transcription: "|wɒt| |əˈbaʊt|", translate: "Wie wär's mit...?; Was ist mit...?", example: "What about a new room in the loft?"},
    {id: 21, english: "afternoon", transcription: "|ˌæftərˈnuːn|", translate: "Nachmittag", example: "morning - afternoon - evening"},
    {id: 22, english: "to look for", transcription: "", translate: "suchen nach", example: ""},
    {id: 23, english: "to snore", transcription: "|snɔː|", translate: "schnarchen", example: ""},
    {id: 24, english: "roommate", transcription: "|ˈrʊmˌmeɪt|", translate: "Zimmergenosse/Zimmergenossin", example: "Jay can't sleep because his roommate snores."},
    {id: 25, english: "coach", transcription: "|kəʊtʃ|", translate: "Trainer/-in", example: "A coach gives help in a sport."},
    {id: 26, english: "last", transcription: "|lɑːst|", translate: "letzte/-r/-s", example: ""},
    {id: 27, english: "tomorrow", transcription: "|təˈmɒrəʊ|", translate: "morgen", example: "Today is Friday. Tomorrow is Saturday."},
    {id: 28, english: "this is how you (do)", transcription: "", translate: "so machst du...", example: "This is how you do this exercise."},
    {id: 29, english: "to tidy", transcription: "|ˈtaɪdɪ|", translate: "aufräumen; in Ordnung bringen", example: "Can you tidy your room, please, Olivia?"},
    {id: 30, english: "by (bike)", transcription: "|baɪ|", translate: "mit (dem Fahrrad)", example: "Let's go by car."},
    {id: 31, english: "cheese", transcription: "|tʃiːz|", translate: "Käse", example: "Mice love cheese."},
    {id: 32, english: "because", transcription: "|bɪˈkɔːz|", translate: "weil; da", example: "I like Lou because she's so cute!"},
    {id: 33, english: "to think", transcription: "|θɪŋk|", translate: "denken; nachdenken", example: "A problem? First stop and think! There's always an answer."},
    {id: 34, english: "to give", transcription: "|ɡɪv|", translate: "geben; schenken", example: "Can you give me a biscuit, please?"},
    {id: 35, english: "to laugh", transcription: "|lɑːf|", translate: "lachen", example: "Don't laugh at me!"},
    {id: 36, english: "It's your turn", transcription: "", translate: "Du bist dran", example: ""},
    {id: 37, english: "to know", transcription: "|nəʊ|", translate: "kennen; wissen", example: "I know Luke. He's the funny boy with the nice dog."},
    {id: 38, english: "much", transcription: "|mʌtʃ|", translate: "viel", example: "I haven't got much time."},
    {id: 39, english: "really", transcription: "|ˈriːəlɪ|", translate: "wirklich", example: "It's very good. I really like it."},
    {id: 40, english: "just", transcription: "|dʒʌst|", translate: "gerade; nur; einfach", example: ""},
    {id: 41, english: "popular", transcription: "|ˈpɑːpjələr|", translate: "beliebt; populär", example: "The students and teacher like Jay. He's popular."},
    {id: 42, english: "to be jealous", transcription: "|ˈdʒeləs|", translate: "eifersüchtig sein (auf)", example: "Is Luke jealous of Jay?"},
    {id: 43, english: "sure", transcription: "|ʃʊə|", translate: "sicher", example: "Where is the book? -I'm sure it's in you bag."},
    {id: 44, english: "poem", transcription: "|ˈpəʊɪm|", translate: "Gedicht", example: ""},
    {id: 45, english: "presentation", transcription: "|ˌpriːzenˈteɪʃn|", translate: "Präsentation; Vortrag", example: ""},
    {id: 46, english: "to work", transcription: "|wɜːk|", translate: "arbeiten", example: "Let's work in the garden!"},
    {id: 47, english: "before", transcription: "|bɪˈfɔː|", translate: "vor (zeitlich); bevor", example: "We've got English before lunch."},
    {id: 48, english: "to need", transcription: "|niːd|", translate: "brauchen; benötigen", example: "Let's make dialogues. -Ok, but I need a partner."},
    {id: 49, english: "spelling", transcription: "|ˈspelɪŋ|", translate: "Rechtschreibung", example: ""},
    {id: 50, english: "to practise", transcription: "|ˈpræktɪs|", translate: "üben; trainieren", example: "First practise the dialogue, then present it."},
    {id: 50, english: "never", transcription: "[ˈnevə]", translate: "nie; niemals", example: "He never turned up."},
]